# The workflow will now only run when:
#   - Pushed to main branch AND the commit message contains --publish
#   - Or manually triggered via workflow_dispatch
#
name: Deploy to Firefox Add-ons Store

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '--publish')

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          # cache: 'npm'

      - name: Install dependencies
        run: npm install -g web-ext@latest

      - name: Verify extension
        run: web-ext lint

      - name: Build package
        run: web-ext build --overwrite-dest
        env:
          NODE_ENV: production

      - name: Publish to Firefox Add-ons
        run: |
          echo "Publishing version $(jq -r .version manifest.json)"
          web-ext sign \
            --api-key ${{ secrets.MOZILLA_JWT_ISSUER }} \
            --api-secret ${{ secrets.MOZILLA_JWT_SECRET }} \
            --source-dir ./ \
            --timeout 600000  # 10 minute timeout
        env:
          WEB_EXT_CHANNEL: listed
          WEB_EXT_SIGN_TIMEOUT: 600000